### PR TITLE
Avoid displaying message multiple times

### PR DESCRIPTION
**Pull request by laulaz**
This refs fourdigits/collective.cookiecuttr#16

### CODE REVIEW

**Comment by laulaz** [comment]
@kingel @erral @nightmarebadger Could you review / merge this pull request ?  and make a new release please ?

Thank you for your help.

**Comment by erral** [comment]
LGTM

**Comment by kingel** [comment]
sorry for not responding earlier, i turned off github notifications because all the plone repos are killing me, ill see that i can make a pypi release todat

**Comment by laulaz** [comment]
Thank you both !

**Comment by kingel** [comment]
I made a release (it is on pypi)

we're not doing plone anymore so i think i should move this to the collective, ill try to look into that

**Pull request merged**
